spring.application.name=Hogwarts
spring.datasource.url=jdbc:postgresql://urlReal100%-MarcianitoBailando.com:5432/hogwarts
spring.datasource.username=therealAdmin
spring.datasource.password=admin-1
springdoc.swagger-ui.path=/hogwarts/documentacion